### ISSUE TITLE
Please create a stable tag + release :)

### ISSUE THREAD

**Issue by mneuhaus** [DavidBadura/Fixtures#12]
Could you maybe create a stable tag + release in order to have a "safe" relation through composer? :)

**Comment by mneuhaus** [comment]
pretty please? :)

**Comment by DavidBadura** [comment]
i will do this in next week :+1:

**Comment by DavidBadura** [comment]
done :-)

**Comment by mneuhaus** [comment]
:+1:  thanks :)
